version: '3.8'

services:
  configsvr0:
    container_name: configsvr0
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db/dbms1
    ports:
      - 40001:27017
    volumes:
      - configsvr0:/data/db/dbms1

  configsvr1:
    container_name: configsvr1
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db/dbms2
    ports:
      - 40002:27017
    volumes:
      - configsvr1:/data/db/dbms2

volumes:
  configsvr0: {}
  configsvr1: {}
