version: '3.8'

services:
  mongos:
    container_name: router
    image: mongo
    command: mongos --configdb cfgrs/192.168.1.2:40001,192.168.1.2:40002 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 60000:27017