version: "3.8"

services:
 redis:
    image: redis
    container_name: cache
    command: redis-server
    ports:
     - "6379:6379"
    volumes:
     - $PWD/redis_cache-data:/var/lib/redis_cache
     - $PWD/redis_cache.conf:/usr/local/etc/redis_cache/redis_cache.conf
    environment:
     - REDIS_REPLICATION_MODE=master
